Repository Totodore/socketioxide, pull requests merged in 2023-12, with the labels that each got.

#188 Disconnect dynamic handlers
  examples/chat/src/main.rs
  examples/private-messaging/src/handlers.rs
  socketioxide/src/handler/disconnect.rs
  socketioxide/src/handler/extract.rs
  socketioxide/src/handler/mod.rs
  socketioxide/src/layer.rs
  socketioxide/src/lib.rs
  socketioxide/src/service.rs
  socketioxide/src/socket.rs
  socketioxide/tests/disconnect_reason.rs
Labels: enhancement

#190 Fix async handlers not run
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  e2e/socketioxide/socketioxide.rs
  socketioxide/Cargo.toml
  socketioxide/src/handler/message.rs
Labels: bug

#194 feat(socketio/state): global state implementation backed by a `state::TypeMap`
  Cargo.lock
  examples/angular-todomvc/Cargo.toml
  examples/angular-todomvc/src/main.rs
  examples/basic-crud-application/Cargo.toml
  examples/basic-crud-application/src/handlers/todo.rs
  examples/basic-crud-application/src/main.rs
  examples/chat/Cargo.toml
  examples/chat/src/main.rs
  examples/private-messaging/Cargo.toml
  examples/private-messaging/src/handlers.rs
  examples/private-messaging/src/main.rs
  examples/private-messaging/src/store.rs
  socketioxide/Cargo.toml
  socketioxide/src/client.rs
  socketioxide/src/handler/extract.rs
  socketioxide/src/io.rs
  socketioxide/src/lib.rs
  socketioxide/src/state.rs
  socketioxide/tests/extractors.rs
  socketioxide/tests/fixture.rs
Labels: enhancement

#196 Migration to hyper 1.0
  .github/workflows/github-ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  e2e/engineioxide/Cargo.toml
  e2e/engineioxide/engineioxide-hyper-v04.rs
  e2e/engineioxide/engineioxide.rs
  e2e/socketioxide/Cargo.toml
  e2e/socketioxide/socketioxide.rs
  engineioxide/Cargo.toml
  engineioxide/Readme.md
  engineioxide/src/body.rs
  engineioxide/src/body/mod.rs
  engineioxide/src/body/request.rs
  engineioxide/src/body/response.rs
  engineioxide/src/errors.rs
  engineioxide/src/layer.rs
  engineioxide/src/service/futures.rs
  engineioxide/src/service/hyper_v1.rs
  engineioxide/src/service/mod.rs
  engineioxide/src/service/parser.rs
  engineioxide/src/transport/polling/mod.rs
  engineioxide/src/transport/polling/payload/decoder.rs
  engineioxide/src/transport/ws.rs
  engineioxide/src/transport/ws/tokio_io.rs
  engineioxide/tests/disconnect_reason.rs
  engineioxide/tests/fixture.rs
  examples/angular-todomvc/Cargo.toml
  examples/angular-todomvc/src/main.rs
  examples/axum-echo/axum_echo.rs
  examples/background-task/src/main.rs
  examples/basic-crud-application/Cargo.toml
  examples/basic-crud-application/src/main.rs
  examples/chat/Cargo.toml
  examples/chat/src/main.rs
  examples/hyper-echo/Cargo.toml
  examples/hyper-echo/hyper_echo.rs
  examples/hyper-v1-echo/Cargo.toml
  examples/hyper-v1-echo/hyper_v1_echo.rs
  examples/private-messaging/Cargo.toml
  examples/private-messaging/src/main.rs
  examples/salvo-echo/Cargo.toml
  examples/salvo-echo/salvo_echo.rs
  examples/warp-echo/Cargo.toml
  examples/warp-echo/warp_echo.rs
  examples/whiteboard/Cargo.toml
  examples/whiteboard/src/main.rs
  socketioxide/Cargo.toml
  socketioxide/src/hyper_v1.rs
  socketioxide/src/io.rs
  socketioxide/src/layer.rs
  socketioxide/src/lib.rs
  socketioxide/src/service.rs
  socketioxide/tests/disconnect_reason.rs
  socketioxide/tests/extractors.rs
  socketioxide/tests/fixture.rs
Labels: dependencies

#199 doc(socketio/extract): add missing extractors to the list
  socketioxide/src/handler/extract.rs
  socketioxide/src/lib.rs
Labels: documentation

#200 chore(deps): switch to `pin-project-lite` for Pin Projection
  Cargo.lock
  Cargo.toml
  engineioxide/Cargo.toml
  engineioxide/src/body.rs
  engineioxide/src/service/futures.rs
Labels: dependencies

#202 Fix version compatibility (Axum - Hyper -Socketioxide)
  README.md
Labels: documentation

#205 refactor: service implementation
  engineioxide/src/service/mod.rs
  socketioxide/src/service.rs
Labels: refactoring

#203 chore: add viz-echo example
  Cargo.toml
  README.md
  engineioxide/src/service/mod.rs
  examples/viz-echo/Cargo.toml
  examples/viz-echo/viz_echo.rs
  socketioxide/Cargo.toml
  socketioxide/benches/packet_decode.rs
  socketioxide/benches/packet_encode.rs
Labels: documentation

#219 test(socketio): improve testing by directly using the `rust_socketio` client
  Cargo.toml
  socketioxide/Cargo.toml
  socketioxide/tests/extractors.rs
  socketioxide/tests/fixture.rs
  socketioxide/tests/utils.rs
Labels: socketio-v4, socketio-v5
