Repository Totodore/socketioxide, pull requests merged in 2023-10, with the labels that each got.

#93 feat: cheaply clonable io struct
  CHANGELOG.md
  Cargo.lock
  README.md
  e2e/Cargo.toml
  e2e/src/engineioxide.rs
  e2e/src/socketioxide.rs
  engineioxide/Cargo.toml
  engineioxide/benches/benchmark_polling.rs
  engineioxide/src/config.rs
  engineioxide/src/engine.rs
  engineioxide/src/handler.rs
  engineioxide/src/layer.rs
  engineioxide/src/lib.rs
  engineioxide/src/packet.rs
  engineioxide/src/payload/encoder.rs
  engineioxide/src/socket.rs
  engineioxide/src/utils.rs
  engineioxide/tests/disconnect_reason.rs
  examples/Cargo.toml
  examples/src/chat/handlers.rs
  examples/src/chat/main.rs
  examples/src/engineio-echo/axum_echo.rs
  examples/src/engineio-echo/hyper_echo.rs
  examples/src/engineio-echo/warp_echo.rs
  examples/src/socketio-echo/axum_echo.rs
  examples/src/socketio-echo/hyper_echo.rs
  examples/src/socketio-echo/warp_echo.rs
  socketioxide/Cargo.toml
  socketioxide/src/adapter.rs
  socketioxide/src/client.rs
  socketioxide/src/config.rs
  socketioxide/src/errors.rs
  socketioxide/src/handler.rs
  socketioxide/src/handshake.rs
  socketioxide/src/io.rs
  socketioxide/src/layer.rs
  socketioxide/src/lib.rs
  socketioxide/src/ns.rs
  socketioxide/src/operators.rs
  socketioxide/src/packet.rs
  socketioxide/src/service.rs
  socketioxide/src/socket.rs
  socketioxide/tests/disconnect_reason.rs
  socketioxide/tests/fixture.rs
Labels: enhancement

#105 fix(clippy): issue #104
  socketioxide/src/adapter.rs
Labels: refactoring

#52 feat(socketioxide/v4): implement SocketIO V4 (closes #51)
  .github/workflows/engineio-ci.yml
  .github/workflows/github-ci.yml
  .github/workflows/rust-clippy.yml
  .github/workflows/socketio-ci.yml
  README.md
  e2e/Cargo.toml
  engineioxide/src/lib.rs
  socketioxide/Cargo.toml
  socketioxide/src/client.rs
  socketioxide/src/errors.rs
  socketioxide/src/handler.rs
  socketioxide/src/io.rs
  socketioxide/src/lib.rs
  socketioxide/src/ns.rs
  socketioxide/src/packet.rs
Labels: enhancement

#114 fix: apply max payload option when encoding (fix #113)
  engineioxide/src/lib.rs
  engineioxide/src/packet.rs
  engineioxide/src/peekable.rs
  engineioxide/src/socket.rs
  engineioxide/src/transport/polling/mod.rs
  engineioxide/src/transport/polling/payload/encoder.rs
  engineioxide/src/transport/polling/payload/mod.rs
Labels: bug

#123 fix(socketio/socket): create a different socket id for each ns
  engineioxide/src/socket.rs
  socketioxide/src/client.rs
  socketioxide/src/errors.rs
  socketioxide/src/ns.rs
  socketioxide/src/socket.rs
Labels: bug, socketio-v5

#124 feat(socketio/ns): store ns path and rooms as `Cow<'static, str>`
  Cargo.lock
  socketioxide/Cargo.toml
  socketioxide/benches/packet_decode.rs
  socketioxide/benches/packet_encode.rs
  socketioxide/src/adapter.rs
  socketioxide/src/client.rs
  socketioxide/src/handler.rs
  socketioxide/src/io.rs
  socketioxide/src/ns.rs
  socketioxide/src/operators.rs
  socketioxide/src/packet.rs
  socketioxide/src/service.rs
  socketioxide/src/socket.rs
Labels: enhancement
